# Generated by Django 4.0.3 on 2022-03-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linkedin_Profile_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_navigator_link', models.URLField(max_length=300)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('linkedin_link', models.URLField()),
                ('message_sent', models.BooleanField(default=False)),
                ('follow_up_1', models.BooleanField(default=False)),
                ('follow_up_2', models.BooleanField(default=False)),
                ('follow_up_3', models.BooleanField(default=False)),
                ('replied', models.BooleanField(default=False)),
                ('last_message', models.DateField(blank=True, null=True)),
                ('error', models.BooleanField(default=False)),
            ],
        ),
    ]
