# Generated by Django 4.0.3 on 2022-03-17 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0002_linkedin_profile_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linkedin_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_account', models.CharField(blank=True, default='', max_length=200)),
                ('linkedin_password', models.CharField(blank=True, default='', max_length=100)),
                ('campaign', models.BooleanField(default=False)),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
