# Generated by Django 4.0.3 on 2022-03-17 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0003_linkedin_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedin_account',
            name='account',
        ),
        migrations.AddField(
            model_name='customuser',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Publication.linkedin_account'),
        ),
    ]
