# Generated by Django 4.0.3 on 2022-03-17 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0004_remove_linkedin_account_account_customuser_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='account',
        ),
        migrations.AddField(
            model_name='linkedin_account',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
