# Generated by Django 4.0.3 on 2022-03-17 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0005_remove_customuser_account_linkedin_account_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedin_profile_info',
            name='associated_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Publication.linkedin_account'),
        ),
    ]
