# Generated by Django 4.0.3 on 2022-03-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0008_linkedin_account_follow_up_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedin_account',
            name='proxy_host',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='linkedin_account',
            name='proxy_pass',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='linkedin_account',
            name='proxy_port',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='linkedin_account',
            name='proxy_use',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='linkedin_account',
            name='proxy_user',
            field=models.TextField(default=''),
        ),
    ]
