# Generated by Django 4.0.3 on 2022-03-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0010_alter_linkedin_account_proxy_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedin_account',
            name='active_follow_up_1',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='linkedin_account',
            name='active_follow_up_2',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='linkedin_account',
            name='active_follow_up_3',
            field=models.BooleanField(default='False'),
        ),
    ]
