# Generated by Django 4.0.3 on 2022-03-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0011_linkedin_account_active_follow_up_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedin_account',
            name='message1',
            field=models.TextField(default='', max_length=200),
        ),
    ]
